<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ViewVolunteers.aspx.cs" Inherits="Admin_Volunteers" MasterPageFile="~/Admin/AdminMaster.master" Title="Volunteers"%>

<asp:Content ContentPlaceHolderID="content_body" ID="ViewVolunteers" runat="server" >


    <link href="css/ViewAllUsers.css" rel="stylesheet" />
    <script src="Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="Scripts/ViewVolunteers.js"></script>

    <div>
    
        <div id="div_main_contianer">            <!-- The main container--> 
           
            
            <div id="div_middle">                <!-- The Middle Body --> 
                
                
               
                
                
                <div id="div_menu_bar">          <!-- Admin Menu Bar --> 
                    
                    <ul> 
                        <li id="li_1"> <a href="AdminHome.aspx" class="a_menu" id="a_menu_Home"> Home </a> </li> 
                        <li id="li_2"> <a href="ViewAllUsers.aspx" class="a_menu" id="a_menu_allUsers"> All Users </a> </li>  
                        <li id="li_3"> <a href="ViewBloggers.aspx" class="a_menu" id="a_menu_bloggers"> Bloggers </a> </li>  
                        <li id="li_4"> <a href="ViewVolunteers.aspx" class="a_menu" id="a_menu_volunteers"> Volunteers </a> </li>  
                       
                    </ul> 
                    
                </div>                           <!-- End OF Admin Menu Bar --> 
                
                
                
                
                <div id="div_volunteerlist_container" style="float:right;margin-top:17px;overflow:auto">           <!-- User list container -->
                    <asp:ScriptManager ID="volunteerview" runat="server"></asp:ScriptManager>
                    <asp:UpdatePanel ID="allvolunteerview" runat="server"><ContentTemplate>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" Height="393px" AllowPaging="true" PageSize="6" CellPadding="4" CssClass="auto-style1" OnRowDeleting="GridView1_RowDeleting" Width="766px" ForeColor="#333333" GridLines="None" OnRowDataBound="GridView1_RowDataBound" CellSpacing="2" OnPageIndexChanging="GridView1_PageIndexChanging">
                          <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                          <EditRowStyle BackColor="#999999" />
               <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle ForeColor="#333333" BackColor="#F7F6F3" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                        <pagersettings mode="NumericFirstLast" position="Bottom"   pagebuttoncount="3"  />
                           <pagerstyle backcolor="RoyalBlue" height="25px"     verticalalign="Bottom"   horizontalalign="Center"/>

            </asp:GridView>
                        </ContentTemplate></asp:UpdatePanel>
                    </div>                   <!-- End of user list container --> 
                


               </div>                               <!-- End OF The Middle Body --> 
            

    </div>
   </div>
 </asp:Content>
        